### ISSUE TITLE
Environment files to ease testing and development process

### ISSUE THREAD

**Issue by fia0** [EmbeddedEnterprises/burrow#9]
It'd would be a nice to have for `burrow` to be able to load environment files, defining multiple environment variables. Maybe something like including it as part of the `burrow.yaml` config:
```
name: name
version: 0.1.0
description: desc
authors:
- ...
license: ""
package:
  include: []
args:
  run: ""
  go:
    test: ""
    build: ""
    doc: ""
    vet: ""
    fmt: -s
  glide:
    install: ""
    update: ""
    get: ""
  git:
    tag: -s -m 'Update version'
    clone: ""
env: $PWD/test.env
```

Of course loading the variables manually or with `smartcd` and such is possible, but it would offer `burrow` a nice touch by relieving the user of this.

@fin-ger
